Feature/graphql convention
creatrip/culture pull request #13
Opened 2020-11-19 02:56 UTC by dleo9307

- graphql 컨벤션에 대해 간단하게 정의했습니다. 추가사항 및 피드백 부탁드리겠습니다.

2020-11-19 03:03 UTC, yjb94 requested changes

2020-11-19 03:03 UTC, yjb94 commented on code-convention/graphql/README.md
> +EX)도메인을 Merchandsie라고 가정했을때
```suggestion
EX)도메인을 Merchandise라고 가정했을때
```

2020-11-19 05:11 UTC, yunseop-kim approved these changes

2020-11-19 05:40 UTC, yjb94 approved these changes

2020-11-23 01:18 UTC, kyue0207 approved these changes

2020-11-23 01:24 UTC, siner308 commented on code-convention/graphql/README.md
> +## DTO 정의
```suggestion
```

**[⬆ back to top](#table-of-contents)**

## DTO 정의
```

2020-11-23 01:24 UTC, siner308 commented on code-convention/graphql/README.md
> +- 1.1 M:N 관계에서의 추가, 삭제 뮤테이션
![image](https://user-images.githubusercontent.com/34048253/99922806-c9808a00-2d75-11eb-8c02-225324858135.png)

여기 두 부분을 맞춰줘야 실제 링크로 동작해용~ 공백은 `-` 로 대체 해야했던것같아요

2020-11-23 01:32 UTC, dleo9307 commented on code-convention/graphql/README.md
> +## DTO 정의
https://github.com/creatrip/culture/pull/13/commits/dcf156621bef51e26797be435afb2e8d0d35dd90
적용했습니다~

2020-11-23 01:33 UTC, dleo9307 commented on code-convention/graphql/README.md
> +- 1.1 M:N 관계에서의 추가, 삭제 뮤테이션
https://github.com/creatrip/culture/pull/13/commits/dcf156621bef51e26797be435afb2e8d0d35dd90
적용했습니다~

2020-11-23 02:27 UTC, milban commented on code-convention/graphql/README.md
> +```
1:N일때 addAToB 라는 컨벤션을 가져가게 되면, B에서 A를 연결하고 싶으면 어떡하나용? addBToA라는 mutation을 만들어주시나용?

M:N이든 1:N이 아닌 단방향 연결인지, 양방향 연결인지에 따라 달라져야 할 것 같은 느낌적인 느낌입니당.

2020-11-23 04:03 UTC, siner308 commented on code-convention/graphql/README.md
> +```
AToB라는 단방향 relation이 반대방향으로도 연결될 일이 있나요? 그건 잘못된 스키마 설계라고 생각돼요

2020-11-23 04:07 UTC, dleo9307 commented on code-convention/graphql/README.md
> +```
정현님 의견에 동의합니다.
일단 반대방향으로 서로 연결된다고 한다면 A서비스(객체)에서 B서비스(객체)를  참조하고 B서비스에서 A서비스를 참조할 가능성이 높아지기 떄문에 최대한 그러한 설계를 하지 않는것이 좋다고 생각합니다.

2020-11-23 04:08 UTC, milban commented on code-convention/graphql/README.md
> +```
단뱡향 연결이 양방향 연결이 되는 경우는 현재 저희 회사에서는 몇 번 있었습니당. 😢

제가 질문하고 싶었던 것이 잘 전달되지 않은 것 같아서 부가설명할게용!
제가 궁금한 것은 M:N, 1:N 둘 다 양방향일 수 있고, 단방향일 수도 있다고 생각합니다. M:N, 1:N은 개수를 나타내는 것이지 방향을 나타내는 것은 아니지 않나용? 그런데 지금 문서는 M:N일 때는 양방향인 것을 묵시적으로 의미하고, 1:N일 때는 단뱡향인 것을 묵시적으로 나타내는 형태라서용.

2020-11-23 06:19 UTC, dleo9307 commented on code-convention/graphql/README.md
> +}
https://github.com/creatrip/culture/pull/13/commits/481d3a43e2281e8e8f5213283d56936cb3200fbd
적용했습니당

2020-11-23 06:20 UTC, milban commented on code-convention/graphql/README.md
> +```
@fuzes  이해했습니당!
그러면 이제 domain <-> domain은 무조건 M:N의 컨벤션을 따르고, domain <-> subdomain은 1:N의 컨벤션을 따른다고 생각하면 될까용?

2020-11-23 06:21 UTC, fuzes commented on code-convention/graphql/README.md
> +```
@milban 넵 맞아용

2020-11-23 06:21 UTC, fuzes commented on code-convention/graphql/README.md
> +}
@milban @yjb94 @yunseop-kim @ssoheej 이 부분도 확인 부탁드릴게요~~

2020-11-23 06:21 UTC, milban approved these changes
고생하셨습니당 😎

2020-11-23 06:22 UTC, yunseop-kim commented
수고하셨습니다

2020-11-23 06:22 UTC, dleo9307 commented on code-convention/graphql/README.md
> +```
기존꺼는 나중에 시간 되면 전부 바꾸는걸로 ㅠㅠ

2020-11-23 06:23 UTC, milban commented on code-convention/graphql/README.md
> +}
지금까지 `input`이었던 것 같은데 `data`로 바뀐 이유가 있나용?
```graphql
CreateMerchandiseArgs{
 input: CreateMerchandiseInput
}

CreateMerchandiseInput {
   name: string
   language: LagnuageType
}
```

2020-11-23 06:43 UTC, dleo9307 commented on code-convention/graphql/README.md
> +}
https://github.com/creatrip/culture/pull/13/commits/b3190c59c48dd288c030b62504a438210a30ea49
일단 제거했습니다.

2020-11-23 06:44 UTC, dleo9307 commented on code-convention/graphql/README.md
> +}
https://github.com/creatrip/culture/pull/13/commits/825727419b79723759df85ccc44f11f9e010a449
최종

2020-11-23 07:40 UTC, yjb94 approved these changes
LGTM 👍

2020-11-24 01:13 UTC, fuzes approved these changes

2020-11-24 01:48 UTC, ssoheej commented on code-convention/graphql/README.md
> +추가 -> linkAandB
linkAwithB가 맞지않나용...?

늦어서 죄송합니당.. 😥

2020-11-24 01:48 UTC, ssoheej commented on code-convention/graphql/README.md
> +추가 -> linkAandB
link와 함께 쓰이는 것들은
link to
link with 로 알고 있습니당!

2020-11-24 02:21 UTC, dleo9307 commented on code-convention/graphql/README.md
> +추가 -> linkAandB
link a with b -> a와 b를 연결
link a to b -> a에서 b로 연결
흠 그렇네요 영어 문법상 link는 to 또는 with와 함께 쓸수있네용
link a with b 가 맞는 표현인듯하네요...

2020-11-24 02:21 UTC, yjb94 commented on code-convention/graphql/README.md
> +추가 -> linkAandB
문법상은 with가 맞긴 한데, 저만 그럴 수도 있지만 프로그래밍 언어에서 함수명 정할 때 1:N은 to, N:M은 and가 자연스러운 것 같은 느낌적인 느낌이 있습니다. 또 메소드명에서 `doSomethingAwithB` 에서처럼 with를 쓰면 B를 사용해서 A를 어떻게 하는 로직이 들어가야 될 것 같은 느낌입니다.

2020-11-24 02:23 UTC, dleo9307 commented on code-convention/graphql/README.md
> +추가 -> linkAandB
@fuzes @siner308 @milban @yunseop-kim 다른분들 의견을 어떠신가용?

2020-11-24 02:29 UTC, milban commented on code-convention/graphql/README.md
> +추가 -> linkAandB
https://www.oxfordlearnersdictionaries.com/definition/american_english/link_2
위 링크에 따르면 link A and B 도 쓰이긴 하나보네용....

2020-11-24 02:54 UTC, siner308 commented on code-convention/graphql/README.md
> +추가 -> linkAandB
@milban 링크의 자료 저도 찾아보았는데, A and B에 대해서만 (together)라고 명시가 되어있기도 하고, 2번 케이스에 대해서는 to/with로 to와 with가 같이 쓰이는 경우도 있으니 and를 사용하는게 확실하게 전달할 가능성이 좀더 있지 않을까 싶네용

2020-11-24 05:37 UTC, ssoheej commented on code-convention/graphql/README.md
> +추가 -> linkAandB
and가 전달성이 더 좋고 문법상 존재한다면 and도 나쁘지 않을 것 같아용!

2020-11-27 01:10 UTC, siner308 approved these changes
수고하셨습니다~!! 🙌

2020-11-27 11:21 UTC, yjb94 approved these changes

2020-11-30 01:28 UTC, kyue0207 approved these changes

2020-12-01 01:10 UTC, yunseop-kim approved these changes

2021-02-23 06:48 UTC, closed without merging